set(FILE_LINES
	"/*"
 	" * DO NOT EDIT"
 	" * This file was generated by gen-managed.sh ${IN_PUBLISH_DIR}"
 	" */"
)
file(GLOB DLL_FILES "${IN_PUBLISH_DIR}/*.dll")
foreach(lib IN LISTS DLL_FILES)
	get_filename_component(lib_name ${lib} NAME)
	if(lib_name STREQUAL "System.Private.CoreLib.dll")
		continue()
	endif()
	list(APPEND FILE_LINES "TRUSTED_PLATFORM_ASSEMBLY(\"${lib}\")")
endforeach()

string(REPLACE ";" "\n" FILE_CONTENTS "${FILE_LINES}")
file(WRITE "${OUT_HEADER}" "${FILE_CONTENTS}")